# Generated by Django 2.2.5 on 2019-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('AND', 'Android Developer'), ('DES', 'Designer'), ('IOS', 'IOS Developer'), ('JAV', 'Java Developer'), ('PHP', 'PHP Developer'), ('PYT', 'Python Developer'), ('RAI', 'Rails Developer'), ('WOR', 'Wordpress Developer'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
