# Generated by Django 2.2.5 on 2019-10-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20191008_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_filled',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Applicant'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='NEW', max_length=3),
        ),
    ]
