# Generated by Django 2.2.5 on 2019-10-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191011_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_filled',
            field=models.BooleanField(default=False),
        ),
    ]
