# Generated by Django 2.2.5 on 2019-10-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
