# Generated by Django 2.2.5 on 2019-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/default_pic.jpg', upload_to='profile_picture'),
        ),
    ]
