# Generated by Django 2.2.5 on 2019-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills',
            field=models.CharField(choices=[('AND', 'Android Developer'), ('DES', 'Designer'), ('IOS', 'IOS Developer'), ('JAV', 'Java Developer'), ('PHP', 'PHP Developer'), ('PYT', 'Python Developer'), ('RAI', 'Rails Developer'), ('WOR', 'Wordpress Developer'), ('OTH', 'Other')], max_length=3),
        ),
    ]
